nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['https://api.partage-solidaire-akouda.continuousnet.com'] # Ajoutez vos domaines frontend ici
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': ~